config/routes.rb
Rails.application.routes.draw do
 # scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

 scope ":locale", locale: /en|ru/ do	

	root 'products#index'
	get 'products/show/:id' => 'products#show', as: 'products_show'
	get 'categories/show/:id' => 'categories#show', as: 'categories_show'

	namespace :admin do
    	root 'products#index'
    	resources :products
    	resources :categories
  	end
end
	devise_for :users
	match "*path", to: redirect("/#{I18n.default_locale}/%{path}"), via: :all	
    match "", to: redirect("/#{I18n.default_locale}/"), via: :all
end














# root 'posts#index'	  
# resources :posts do
# member do
# get 'close'	  		
# get 're_open'	  	
# end	  	
# collection do
# get 'search'
# end
# end
# end	

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, presence: true, length: {maximum: 250}
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  validates :title, presence: true,
            length: { maximum: 250 }

  validates :price, presence: true,
            numericality: { greater_than_or_equal_to: 0.01 }

  mount_uploader :image, ProductUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def destroy
    Category.destroy(params[:id])

    redirect_to admin_categories_path
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      save_picture
      redirect_to [:admin, @product]
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      save_picture
      redirect_to [:admin, @product]
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.destroy(params[:id])
    redirect_to admin_products_url
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :image, :category_id)
  end

  def save_picture
    uploaded_file = params[:product][:picture]

    unless uploaded_file.nil?
      new_file_path = Rails.root.join('public', 'uploads', @product.id.to_s)

      File.open(new_file_path, 'wb') do |file|
        file.write uploaded_file.read
      end
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!, :admin_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  private  
  


  def set_locale    
    I18n.locale = params[:locale] if params[:locale].present?  
  end

  def default_url_options(options={})
  { :locale => I18n.locale }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def admin_user
    unless current_user.admin?
      flash[:danger] = "You don't have enough permissions"
      redirect_to root_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  	@category = Category.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.paginate(page: params[:page], per_page: 10)
  end
  
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_image(id)
    if File.exists? Rails.root.join('public', 'uploads', id.to_s)
      "/uploads/#{id}"
    else
      'coming-soon.png'
    end
  end
end

app/views/admin/categories/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1><%= t 'posts.index.category_nav' %> <%= link_to (t 'posts.index.category_btn'), new_admin_category_path, class: 'btn btn-success' %></h1>
  </div>
</div>

<hr />

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th style="width: 100px;">Actions</th>
  </tr>

  <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to (t 'posts.index.delete'), admin_category_path(category), method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      </tr>
  <% end %>
</table>

app/views/admin/categories/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Category</h1>
  </div>
</div>

<hr />

<%= form_for [:admin, @category], html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @category.errors[:name].any? %>">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @category, field_name: :name %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @product.errors[:title].any? %>">
      <%= f.label :title, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :title %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:description].any? %>">
      <%= f.label :description, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :description %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:price].any? %>">
      <%= f.label :price, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :price, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :price %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:category_id].any? %>">
      <%= f.label :category_id, 'Category', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select :category_id, Category.all, :id, :name, {}, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @product, field_name: :category_id %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @product.errors[:picture].any? %>">
      <%= f.label :picture, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.file_field :picture %>
        <%= render 'shared/field_errors', object: @product, field_name: :picture %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
       <%= f.file_field :image %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Edit Product</h1>
  </div>
</div>

<hr />

<%= render 'form' %>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1><%= t 'posts.index.product_nav' %> <%= link_to (t 'posts.index.product_btn'), new_admin_product_path, class: 'btn btn-success' %></h1>
  </div>
</div>

<hr />

<table class="table table-striped">
  <tr>
    <th><%= t 'posts.index.image' %></th>
    <th><%= t 'posts.index.title' %></th>
    <th><%= t 'posts.index.desc' %></th>
    <th><%= t 'posts.index.price' %></th>
    <th><%= t 'posts.index.category' %></th>
    <th><%= t 'posts.index.action' %></th>
  </tr>

  <% @products.each do |product| %>
      <tr>
        <td><%= image_tag "/uploads/#{product.id}", size: '100' %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name %></td>
        <td>
          <%= link_to (t 'posts.index.view'), admin_product_path(product) %>
          <%= link_to (t 'posts.index.edit'), edit_admin_product_path(product) %>
          <%= link_to (t 'posts.index.delete'), admin_product_path(product),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this product?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/admin/products/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Product</h1>
  </div>
</div>

<hr />

<%= render 'form' %>

app/views/admin/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %></p>
<p>
    Price: <b><%= @product.price %></b>
</p>
<p>
    <b>Category: </b> <%= @product.category.name %>
</p>
<div>
    <%= link_to 'Back to list', admin_products_path %>
</div>

app/views/categories/show.html.erb
<% @category.products.each do |product| %>
	<p><b><%= product.title %></b></p>
	<div class="img" style="background-image: url('<%= image_path product_image(product.id) %>');"></div>
	<p><%= product.description %></p>
	<p>
	    Price: <b><%= product.price %></b>
	</p>
	<hr>
<% end %>
	<div>
	    <%= link_to (t 'posts.index.back_show'), root_path %>
	</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop Admin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/admin/navbar' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" ><%= t 'posts.index.sitename' %></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to (t 'posts.index.product_nav'), admin_products_path %></li>
        <li><%= link_to (t 'posts.index.category_nav'), admin_categories_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to (t 'posts.index.viewshop_nav'), root_path %></li>
      </ul>
    </div>
  </div>
</nav>
<center>
<h4><%= link_to_unless_current "English", locale: 'en' %> |
<%= link_to_unless_current "Russian", locale: 'ru' %></h4>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/application/navbar' %>

<div class="container">

  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <% end %>

  <%= yield %>

</div>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to (t 'posts.index.shop_name'), root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Pages links -->
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            <%= t 'posts.index.loggin' %><%= current_user.name %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t 'posts.index.acc' %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li><%= link_to (t 'posts.index.adm_panel'), admin_root_path %></li>
                <% end %>
                <li><%= link_to (t 'posts.index.edit_profile'), edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to (t 'posts.index.sign_out'), destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<center>
<h4><%= link_to_unless_current "English", locale: 'en' %> |
<%= link_to_unless_current "Russian", locale: 'ru' %></h4>
</center>

app/views/products/index.html.erb
<div class="jumbotron">
  <h1><%= t 'posts.index.welcome' %></h1>
  <p><%= t 'posts.index.wel_msg' %></p>
  <p><a href="#" class="btn btn-primary btn-lg"><%= t 'posts.index.learn' %></a></p>
</div>

<div class="row">

  <div class="col-sm-3">
    <div class="panel panel-default" id="cart">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t 'posts.index.category_nav' %></h3>
      </div>
      <div class="panel-body">
        <ul>
        <% Category.all.each do |category| %>
            <li><%= link_to category.name, categories_show_path(category.id) %></a></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="row">
      <div class="col-sm-12 products-pagination">
        <%= will_paginate @products %>
      </div>
    </div>

    <div class="row">
        <% @products.each do |product| %>

        <div class="col-sm-6 product-item">
          <div class="panel panel-default">
            <div class="panel-body">
              <h3><%= product.title %></h3>
              <div class="img" style="background-image: url('<%= image_path product_image(product.id) %>');"></div>
              <h4>$<%= product.price %></h4>
              <p>
                <button class="btn btn-default"><%= link_to (t 'posts.index.view'), products_show_path(product.id) %></button>
                <button class="btn btn-primary"><%= t 'posts.index.cart_add' %></button>
              </p>
            </div>
          </div>
        </div>

        <% end %>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= will_paginate @products %>
      </div>
    </div>
  </div>
  <div class="col-sm-3">
      <div class="panel panel-default" id="cart">
        <div class="panel-heading">
          <h3 class="panel-title"><%= t 'posts.index.cart' %></h3>
        </div>
        <div class="panel-body">
          Your cart is empty
        </div>
      </div>
  </div>
</div>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %></p>
<p>
    Price: <b><%= @product.price %></b>
</p>
<p>
    <b>Category: </b> <%= @product.category.name %>
</p>
<div>
    <%= link_to (t 'posts.index.back_show'), root_path %>
</div>

app/views/shared/_field_errors.html.erb
<% if object.errors[field_name].any? %>
    <ul class="error-messages">
      <% object.errors.full_messages_for(field_name).each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
<% end %>